version: 1
formatters:
  standard:
    format: "%(asctime)s %(levelname)s %(name)s: %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  ai_model_events_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/ai_model_events.log
    maxBytes: 10485760
    backupCount: 3
  forecast_engine_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/forecast_engine.log
    maxBytes: 10485760
    backupCount: 3
  recommendation_service_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/recommendation_service.log
    maxBytes: 10485760
    backupCount: 3
loggers:
  AI_Model_Events:
    level: INFO
    handlers: [console, ai_model_events_file]
    propagate: false
  Forecast_Engine:
    level: INFO
    handlers: [console, forecast_engine_file]
    propagate: false
  Recommendation_Service:
    level: INFO
    handlers: [console, recommendation_service_file]
    propagate: false
root:
  level: WARNING
  handlers: [console]
